# Generated by Django 3.0.6 on 2020-06-22 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Board's name")),
                ('type', models.CharField(blank=True, choices=[('1', 'Programming'), ('2', 'Drawing'), ('3', 'Music')], max_length=1, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Column's name")),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Board's name")),
                ('description', models.TextField(max_length=500)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Column')),
            ],
        ),
        migrations.CreateModel(
            name='TaskParticipate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Mark's name")),
                ('colour', models.CharField(max_length=50, verbose_name="Mark's colour")),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Task')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name="Task's image")),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Task')),
            ],
        ),
    ]
