# Generated by Django 3.0.6 on 2020-06-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='type',
            field=models.CharField(blank=True, choices=[('Programming', 'Programming'), ('Drawing', 'Drawing'), ('Music', 'Music')], max_length=15, null=True),
        ),
    ]
