# Generated by Django 3.1.2 on 2020-12-17 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20200623_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='token',
            field=models.CharField(default=6067174740900710798, max_length=100, unique=True, verbose_name="Board's token"),
        ),
    ]
